# Generated by Django 5.1.1 on 2025-04-06 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDriverAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment_status",
                    models.CharField(choices=[("A", "active"), ("I", "inactive")], default="A", max_length=1),
                ),
                ("begin_at", models.DateField()),
                ("ends_at", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="VehicleTechnician",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("begin_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("car", "Car"),
                            ("truck", "Truck"),
                            ("bus", "Bus"),
                            ("other", "Other"),
                        ],
                        default="car",
                        max_length=10,
                    ),
                ),
                ("vin_number", models.CharField(max_length=17, unique=True)),
                ("vehicle_image", models.ImageField(blank=True, null=True, upload_to="media/vehicles/")),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                ("license_plate_number", models.CharField(max_length=10, unique=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("last_service_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "make", "model"],
            },
        ),
    ]
