# Generated by Django 5.1.1 on 2025-04-06 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0002_initial"),
        ("management", "0001_initial"),
        ("vehicleHub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                related_query_name="vehicle",
                to="vehicleHub.fuel",
            ),
        ),
        migrations.AddField(
            model_name="vehicledriverassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="vehicledriverassignment",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                related_query_name="assignment",
                to="authentication.driver",
            ),
        ),
        migrations.AddField(
            model_name="vehicledriverassignment",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                related_query_name="assignment",
                to="management.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="vehicletechnician",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="vehicletechnician",
            name="managed_vehicles",
            field=models.ManyToManyField(
                related_name="technician", related_query_name="managing_technician", to="management.vehicle"
            ),
        ),
        migrations.AddField(
            model_name="vehicletechnician",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user",
                related_query_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together={("make", "model", "year", "vin_number")},
        ),
        migrations.AddConstraint(
            model_name="vehicledriverassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assignment_status", "A")),
                fields=("vehicle",),
                name="unique_active_vehicle_assignment",
            ),
        ),
    ]
