# Generated by Django 5.1.1 on 2024-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vehicledriverassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vehicletechnician",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
