# Generated by Django 5.1.1 on 2024-10-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_driver_driver_license_document"),
        ("management", "0002_alter_vehicle_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledriverassignment",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                related_query_name="assignment",
                to="authentication.driver",
            ),
        ),
    ]
