# Generated by Django 5.1.1 on 2025-03-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_vehicledriverassignment_driver"),
        ("vehicleHub", "0012_remove_fuel_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                related_query_name="vehicle",
                to="vehicleHub.fuel",
            ),
        ),
    ]
