# Generated by Django 5.1.1 on 2024-09-20 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("management", "0001_initial"),
        ("vehicleHub", "0003_fuel_issuereport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True, verbose_name="Payment date")),
                ("payment_amount", models.PositiveIntegerField(blank=True, null=True, verbose_name="Payment amount")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("C", "Cash"), ("B", "Bank"), ("M", "Mobile")], default="C", max_length=1
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=250, null=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costs",
                        related_query_name="costs",
                        to="vehicleHub.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FuelConsumption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True, verbose_name="Payment date")),
                ("payment_amount", models.PositiveIntegerField(blank=True, null=True, verbose_name="Payment amount")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("C", "Cash"), ("B", "Bank"), ("M", "Mobile")], default="C", max_length=1
                    ),
                ),
                (
                    "quantity_type",
                    models.CharField(choices=[("l", "liter"), ("kWh", "kWh")], default="l", max_length=3),
                ),
                ("quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("fuel_cost", models.PositiveIntegerField(blank=True, null=True, verbose_name="fuel cost")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Fuel Consumption date")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fuel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_consumptions",
                        related_query_name="fuel_consumption",
                        to="vehicleHub.fuel",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_consumptions",
                        related_query_name="fuel_consumption",
                        to="vehicleHub.partner",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_consumptions",
                        related_query_name="fuel_consumption",
                        to="management.vehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True, verbose_name="Payment date")),
                ("payment_amount", models.PositiveIntegerField(blank=True, null=True, verbose_name="Payment amount")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("C", "Cash"), ("B", "Bank"), ("M", "Mobile")], default="C", max_length=1
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True, verbose_name="name")),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "pending"), ("A", "approved"), ("R", "rejected"), ("C", "canceled")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("maintenance_begin_date", models.DateField(blank=True, null=True)),
                ("maintenance_end_date", models.DateField(blank=True, null=True)),
                ("required_issue_report", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenances",
                        related_query_name="maintenance",
                        to="vehicleHub.issuereport",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_maintenances",
                        related_query_name="completed_maintenance",
                        to="vehicleHub.partner",
                        verbose_name="Maintenance partnership",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenances",
                        related_query_name="maintenance",
                        to="management.vehicle",
                    ),
                ),
            ],
            options={
                "unique_together": {("issue_report", "vehicle")},
            },
        ),
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("C", "Cash"), ("B", "Bank"), ("M", "Mobile")], default="C", max_length=1
                    ),
                ),
                ("record_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_records",
                        to="vehicleBudget.documentcost",
                    ),
                ),
                (
                    "fuel_consumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_records",
                        to="vehicleBudget.fuelconsumption",
                    ),
                ),
                (
                    "vehicle_maintenance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_records",
                        to="vehicleBudget.vehiclemaintenance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
