# Generated by Django 5.1.1 on 2024-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleBudget", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentcost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="financialrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="fuelconsumption",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
