# Generated by Django 5.1.1 on 2024-09-20 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Document Name")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INSURANCE_CERTIFICATE", "Insurance Certificate"),
                            ("ROAD_TAX", "Road Tax"),
                            ("VEHICLE_INSPECTION_REPORT", "Vehicle Inspection Report"),
                            ("VEHICLE_REGISTRATION_DOCUMENT", "Vehicle Registration Document"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_category",
                    models.CharField(
                        choices=[("CORE", "Core Document"), ("TRAFFIC_VIOLATION", "Traffic Violation")], max_length=50
                    ),
                ),
                ("issued_to", models.CharField(choices=[("VEHICLE", "Vehicle"), ("DRIVER", "Driver")], max_length=50)),
                ("is_renewable", models.BooleanField(default=True)),
                ("validity_period", models.IntegerField(blank=True, null=True)),
                ("renewal_frequency", models.IntegerField(blank=True, null=True)),
                ("issuing_authority", models.CharField(max_length=100)),
                ("begin_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=250, null=True)),
                ("document_image", models.ImageField(blank=True, null=True, upload_to="media/document_types/")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        related_query_name="document",
                        to="authentication.driver",
                    ),
                ),
                (
                    "issued_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        related_query_name="document",
                        to="management.vehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
