# Generated by Django 5.1.1 on 2025-04-06 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fuel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("GASOLINE", "Gasoline"),
                            ("DIESEL", "Diesel"),
                            ("ELECTRIC", "Electric"),
                            ("OTHER", "Other"),
                        ],
                        default="GASOLINE",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IssueReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Issue Report Name")),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], default="HIGH", max_length=50
                    ),
                ),
                ("report_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_reports",
                        related_query_name="issue_report",
                        to="management.vehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True, verbose_name="Partner Address")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Partner Email")),
                ("website", models.URLField(blank=True, null=True, unique=True, verbose_name="Partner Website")),
                ("phone_number", models.CharField(blank=True, max_length=255, null=True)),
                ("companyNIF", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Document Name")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DRIVER_CERTIFICATE", "Driver Certificate"),
                            ("INSURANCE_CERTIFICATE", "Insurance Certificate"),
                            ("ROAD_TAX", "Road Tax"),
                            ("VEHICLE_INSPECTION_REPORT", "Vehicle Inspection Report"),
                            ("VEHICLE_REGISTRATION_DOCUMENT", "Vehicle Registration Document"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_category",
                    models.CharField(
                        choices=[("core", "Core Document"), ("traffic_violation", "Traffic Violation")], max_length=50
                    ),
                ),
                ("issued_to", models.CharField(choices=[("V", "Vehicle"), ("D", "Driver")], max_length=50)),
                ("is_renewable", models.BooleanField(default=True)),
                ("validity_period", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "renewal_frequency",
                    models.CharField(choices=[("M", "Months"), ("Y", "Years")], default="Y", max_length=50),
                ),
                ("exp_begin_date", models.DateField(blank=True, null=True)),
                ("exp_end_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=250, null=True)),
                ("document_file", models.FileField(blank=True, null=True, upload_to="media/document/")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        related_query_name="document",
                        to="authentication.driver",
                    ),
                ),
                (
                    "issued_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        related_query_name="document",
                        to="management.vehicle",
                    ),
                ),
                (
                    "issuing_authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_documents",
                        related_query_name="issued_document",
                        to="vehicleHub.partner",
                        verbose_name="Issuing Authority",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Partnership Name")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="Start Date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="End Date")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive"), ("TERMINATED", "Terminated")],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                ("is_permanent_partner", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="partner",
            name="partnership",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="vehicleHub.partnership"
            ),
        ),
    ]
