# Generated by Django 5.1.1 on 2024-09-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleHub", "0003_fuel_issuereport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="document_image",
        ),
        migrations.AddField(
            model_name="document",
            name="document_file",
            field=models.FileField(blank=True, null=True, upload_to="media/document/"),
        ),
    ]
