# Generated by Django 5.1.1 on 2024-09-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleHub", "0004_remove_document_document_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="issuing_authority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_documents",
                related_query_name="issued_document",
                to="vehicleHub.partner",
                verbose_name="Issuing Authority",
            ),
        ),
    ]
