# Generated by Django 5.1.1 on 2024-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleHub", "0005_alter_document_issuing_authority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnership",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Partnership Name"),
        ),
    ]
