# Generated by Django 5.1.1 on 2024-09-21 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleHub", "0006_alter_partnership_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="companyNIF",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Partner Email"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="partnership",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="vehicleHub.partnership"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="website",
            field=models.URLField(blank=True, null=True, unique=True, verbose_name="Partner Website"),
        ),
    ]
