# Generated by Django 5.1.1 on 2024-09-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleHub", "0007_alter_partner_companynif_alter_partner_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnership",
            name="is_permanent_partner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="partnership",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="partnership",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start Date"),
        ),
    ]
