# Generated by Django 5.1.1 on 2024-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleHub", "0008_partnership_is_permanent_partner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="renewal_frequency_type",
            field=models.CharField(choices=[("M", "Months"), ("Y", "Years")], default="Y", max_length=50),
        ),
        migrations.AlterField(
            model_name="document",
            name="renewal_frequency",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
