# Generated by Django 5.1.1 on 2024-09-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleHub", "0009_document_renewal_frequency_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="renewal_frequency_type",
        ),
        migrations.AlterField(
            model_name="document",
            name="document_category",
            field=models.CharField(
                choices=[("core", "Core Document"), ("traffic_violation", "Traffic Violation")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="issued_to",
            field=models.CharField(choices=[("V", "Vehicle"), ("D", "Driver")], max_length=50),
        ),
        migrations.AlterField(
            model_name="document",
            name="renewal_frequency",
            field=models.CharField(choices=[("M", "Months"), ("Y", "Years")], default="Y", max_length=50),
        ),
        migrations.AlterField(
            model_name="document",
            name="validity_period",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
