# Generated by Django 5.1.1 on 2025-03-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleHub", "0011_alter_document_created_at_alter_fuel_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuel",
            name="vehicle",
        ),
    ]
