# Generated by Django 5.1.1 on 2025-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleHub", "0012_remove_fuel_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("DRIVER_CERTIFICATE", "Driver Certificate"),
                    ("INSURANCE_CERTIFICATE", "Insurance Certificate"),
                    ("ROAD_TAX", "Road Tax"),
                    ("VEHICLE_INSPECTION_REPORT", "Vehicle Inspection Report"),
                    ("VEHICLE_REGISTRATION_DOCUMENT", "Vehicle Registration Document"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
