# Generated by Django 5.1.1 on 2024-09-20 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("vehicleHub", "0002_rename_begin_date_document_exp_begin_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="driver_license_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner",
                related_query_name="owner",
                to="vehicleHub.document",
            ),
        ),
    ]
