# Generated by Django 5.1.1 on 2025-04-06 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("vehicleHub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="driver_license_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner",
                related_query_name="owner",
                to="vehicleHub.document",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver",
                related_query_name="drivers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accessrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roles",
                related_query_name="role",
                to="authentication.role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="driver",
            unique_together={("user", "driving_license_number")},
        ),
    ]
